use_frameworks!

platform :ios, '8.0'

target 'NavigationBarColor_Example' do
  pod 'NavigationBarColor', :path => '../'

  target 'NavigationBarColor_Tests' do
    inherit! :search_paths

    
  end
end
